spring:

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: xxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxx
    initialization-mode: always
    data: classpath:board-schema.sql

  data:
    mongodb:
      uri: mongodb://localhost:27017/board