spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamhungrybird@gmail.com
    password: teamhungrybird!@#
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
